### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by NN-Binary** [rolag/lockfreehashmap-rs#4]
Hi!

Thanks for the crate, quite amazing!
Is that production ready, to handle millions of concurrent inserts?

Thank you

**Comment by rolag** [comment]
I don't know. I haven't tested it in a production-like environment.

**Comment by NN-Binary** [comment]
Thanks :)

What are the honest limits/flaws of this crate if there is any?

**Comment by rolag** [comment]
It's been a while since I've looked through the code properly, but from what I can remember:

1) The map is resized automatically but only when it's full. This will probably be less efficient than one that was created with `with_capacity()` with a large enough capacity. I've been meaning to fix this but it's a lot more work than I have time for currently.
2) It currently has dependencies on crossbeam libraries from several months ago, which may be buggier or more unstable than the current crossbeam library.

**Comment by NN-Binary** [comment]
Awesome! thanks for the clarifications!
PS: I want to shot you an email, do you mind writting it down i'll email you right away so you can delete it

**Comment by rolag** [comment]
https://gist.github.com/rolag/ef891895c066d0a5f4aa85712fd5d5a6
