### ISSUE TITLE
Benchmark comparisons

### ISSUE THREAD

**Issue by yterradas** [rolag/lockfreehashmap-rs#6]
hi @rolag, 

do you have any benchmarks?  i ask because i have a test that loads a 4.5gb file of different data into multiple RwLock<HashMap<u32, u32>>.  it takes about 58sec.  using LockFreeHashMap<u32, u32> takes minutes, after 15mins i just stop it.  load is done single threaded.  any ideas as to why it is so slow?

**Comment by rolag** [comment]
It is probably slow because the hash map currently only resizes itself whenever it is completely full. So most of the reads/writes are probably contested. You might have better luck instantiating `LockFreeHashMap` using `with_capacity()`.

Unfortunately, I do not have the time to maintain this so I will archive this project for now.
